numpy : 수학 과학용 계산을 위해 만들어진 라이브러리

In [1]:
import numpy as np

In [3]:
# ndarray
a_list=[1, 2.15, '가나다', '123'] # 파이썬 허용
arr = np.array([1,2,3,4])


array([1, 2, 3, 4])

In [6]:
print(type(a_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
# list를 이용 ndarray 생성
my_list1 = [1, 2, 3, 4, 5]
arr2 = np.array(a_list)
print(arr2.dtype)
print(arr1.dtype)

<U32
int32


In [18]:
my_list2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(my_list2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [20]:
arr1.shape

(5,)

In [19]:
arr2.shape

(2, 3)

In [21]:
arr = np.array([1, 2, 3, 4.5])
print(arr.dtype)
print(arr)

float64
[1.  2.  3.  4.5]


In [22]:
arr = np.array([1, 2, 3, 4.5], dtype=int)
print(arr.dtype)
print(arr)

int32
[1 2 3 4]


In [23]:
arr = np.array([1, 2, 3, 4.5, '가나다', '1234'], dtype=int)
print(arr.dtype)
print(arr)

ValueError: invalid literal for int() with base 10: '가나다'

In [24]:
arr = np.array([1, 2, 3, 4.5, '1234'], dtype=int)
print(arr.dtype)
print(arr)

int32
[   1    2    3    4 1234]


In [27]:
list_aa = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype=int)
print(list_aa[3:5])

[4 5]


In [28]:
print(list_aa[-1])

0


In [35]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2.shape)
arr2

(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2[0, 2]

3

In [32]:
arr2[0, 0:3]

array([1, 2, 3])

In [34]:
arr2[:, 3]

array([ 4,  8, 12])

In [36]:
arr = np.array([12, 433, 442, 55, 66, 35, 7565, 7565])
my_idx = [3, 4, 5]
arr[my_idx]

array([55, 66, 35])

In [37]:
bool_list = [False, True, False, True, False, True, False, True]
arr[bool_list]

array([ 433,   55,   35, 7565])

In [41]:
bool_list2 = arr2>4
arr2[bool_list2]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
# arange
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_np = np.array(arr)

In [48]:
arr_np = np.arange(start=0, stop=9+1) # == np.arange(0, 9+1)
print(type(arr_np))
print(arr_np)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [47]:
r = range(1, 10)
print(r)
print(type(r))
print(list(r))

range(1, 10)
<class 'range'>
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [49]:
arr_sample = np.arange(0, 5, 0.5)
arr_sample

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [50]:
arr = np.array([5, 2, 8, 2,5,6,5,6,8,9,9,3,4,41,4,5])
np.sort(arr)

array([ 2,  2,  3,  4,  4,  5,  5,  5,  5,  6,  6,  8,  8,  9,  9, 41])

In [52]:
arr

array([ 5,  2,  8,  2,  5,  6,  5,  6,  8,  9,  9,  3,  4, 41,  4,  5])

In [51]:
np.sort(arr)[::-1]

array([41,  9,  9,  8,  8,  6,  6,  5,  5,  5,  5,  4,  4,  3,  2,  2])

In [57]:
arr2d = np.array([[7,6,5,4],
                 [10, 9, 8, 7],
                 [1,3,2,4]])
arr2d

array([[ 7,  6,  5,  4],
       [10,  9,  8,  7],
       [ 1,  3,  2,  4]])

In [55]:
np.sort(arr2d, axis=0)

array([[ 1,  3,  2,  4],
       [ 7,  6,  5,  4],
       [10,  9,  8,  7]])

In [56]:
np.sort(arr2d, axis=1)

array([[ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [ 1,  2,  3,  4]])

In [58]:
# 정렬된 값을 반환 하지 않고 인덱스를 반환
np.argsort(arr2d, axis=1)

array([[3, 2, 1, 0],
       [3, 2, 1, 0],
       [0, 2, 1, 3]], dtype=int64)

In [59]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])

In [60]:
a + b

array([[5, 7, 9],
       [5, 7, 9]])

In [61]:
a - b

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [64]:
c = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])
a + c

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [62]:
np.sum(a, axis=0)

array([5, 7, 9])

In [63]:
np.sum(a, axis=1)

array([ 6, 15])

In [65]:
a * b

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [69]:
np.dot(a, c)

array([[22, 28],
       [49, 64]])

In [78]:
a, c

(array([[1, 2, 3],
        [1, 2, 3],
        [2, 3, 4]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [73]:
np.cross(a, c)

array([[ -6,   3,   0],
       [-12,   9,  -2],
       [-24,  20,  -3]])

In [71]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [72]:
np.cross(a, b)

array([[ -6,   3,   0],
       [-12,   9,  -2],
       [-24,  20,  -3]])

In [74]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [75]:
b = np.array([[1], [2], [3]])

a * b

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 6,  9, 12]])